#ifndef DPSO_PARAMS_H
#define DPSO_PARAMS_H

#define DPSO_SWARM_SIZE 112
#define DPSO_MAX_ITER 1500
#define DPSO_INERTIA_WEIGHT 0.7
#define DPSO_COGNITIVE_WEIGHT 1.4
#define DPSO_SOCIAL_WEIGHT 1.6
#define DPSO_MIN_VELOCITY_LEN 10
#define DPSO_VELOCITY_SCALE 5
#define DPSO_MUTATION_PROB 0.05
#define DPSO_LOCAL_SEARCH_ATTEMPTS 5

#endif // DPSO_PARAMS_H
